name: Testing
on:
  push:
    branches:
      - version0.1
      - master

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install pymoo>=0.6.0
          pip install -r tests/requirements.txt
      - name: Install paretoflow (DEBUG)
        run: |
          python setup.py install
      - name: isort
        run: |
          python -m  isort . --check --diff
      - name: black
        run: |
          python -m black --check --diff .
      - name: flake8
        run: |
          python -m flake8 .
 